/*
 * 
 *  LICENSE
 * 
 */
package manajemenkomplain.pengguna.detailUser;

import manajemenkomplain.keluhan.detailKeluhan.*;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author link
 */
public class viewDetailUser extends javax.swing.JFrame {

    /**
     * Creates new form viewKeluhan
     */
    public viewDetailUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblIdLevel = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblNoTelp = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setText("User");

        lblIdLevel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdLevel.setText("idLevel        :  [idLevel]");

        lblIdUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdUser.setText("idUser         :  [idUser]");

        lblNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNama.setText("Nama          :  [Nama]");

        lblAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlamat.setText("Alamat        :  [Alamat]");

        lblNoTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNoTelp.setText("No Telpon   :  [NoTelp]");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdUser)
                            .addComponent(lblIdLevel)
                            .addComponent(lblNama)
                            .addComponent(lblAlamat)
                            .addComponent(lblNoTelp))))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addGap(24, 24, 24)
                .addComponent(lblIdUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNama)
                .addGap(11, 11, 11)
                .addComponent(lblAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoTelp)
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDetailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDetailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDetailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDetailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDetailUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblIdLevel;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables


///// getter
    public JButton getBtnBack() {
        return btnBack;
    }


 /// Setter

    public void setLblAlamat(String t) {
        this.lblAlamat.setText("Alamat        :  "+t);
    }

    public void setLblIdLevel(String t) {
        this.lblIdLevel.setText("idLevel        :  "  +t);
    }

    public void setLblIdUser(String t) {
        this.lblIdUser.setText("idUser         :  "+t);
    }

    public void setLblNama(String t) {
        this.lblNama.setText("Nama          :  "+t);
    }

    public void setLblNoTelp(String t) {
        this.lblNoTelp.setText("No Telpon   :  "+t);
    }


   
    
    public void addActionListener(ActionListener x){
        this.btnBack.addActionListener(x);
    }   

    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }

}
