/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemenkomplain.pengguana.tambahKeluhan;

import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Affan
 */
public class ViewTambahKeluhan extends javax.swing.JFrame {

    /**
     * Creates new form ViewTambahKeluhan
     */
    public ViewTambahKeluhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDeskrips = new javax.swing.JTextArea();
        jLabelIdUser = new javax.swing.JLabel();
        jLabelIdKeluhan = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbTemaKeluhan = new javax.swing.JComboBox<>();
        lblKeluhanMendesak = new javax.swing.JLabel();
        ckMendesak = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tambah Keluhan");

        jLabel2.setText("Id_Keluhan");

        jLabel3.setText("Id_User");

        jLabel4.setText("Tema Keluhan");

        jLabel5.setText("Deskripsi");

        textDeskrips.setColumns(20);
        textDeskrips.setRows(5);
        jScrollPane1.setViewportView(textDeskrips);

        jLabelIdUser.setText("jLabel8");

        jLabelIdKeluhan.setText("jLabel9");

        btnTambah.setText("Tambah");

        btnBack.setText("Back");

        cbTemaKeluhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kabel Putus", "Bandwidh Down", "Internet Mati", "Koneksi Tidak Stabil" }));

        lblKeluhanMendesak.setText("Keluhan Mendesak");

        ckMendesak.setText("Mendesak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(lblKeluhanMendesak))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelIdKeluhan)
                                        .addComponent(jLabelIdUser)
                                        .addComponent(cbTemaKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ckMendesak)))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelIdKeluhan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelIdUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbTemaKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeluhanMendesak)
                    .addComponent(ckMendesak))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnBack))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTambahKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTambahKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTambahKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTambahKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTambahKeluhan().setVisible(true);
            }
        });
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }

   
    

    public String getTextDeskrips() {
        return textDeskrips.getText();
    }

    public void setTextDeskrips(String textDeskrips) {
        this.textDeskrips.setText(textDeskrips);
    }

    public String getjLabelIdKeluhan() {
        return jLabelIdKeluhan.getText();
    }

    public void setjLabelIdKeluhan(String jLabelIdKeluhan) {
        this.jLabelIdKeluhan.setText(jLabelIdKeluhan);
    }

    public String getjLabelIdUser() {
        return jLabelIdUser.getText();
    }

    public void setjLabelIdUser(String jLabelIdUser) {
        this.jLabelIdUser.setText(jLabelIdUser);
    }
    
    public void setCkMendesak (boolean b) {
        this.ckMendesak.setSelected(b);
    }
    
    public JCheckBox getCkMendesak () {
        return this.ckMendesak;
    }

    public JComboBox<String> getCbTemaKeluhan () {
        return this.cbTemaKeluhan;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTemaKeluhan;
    private javax.swing.JCheckBox ckMendesak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIdKeluhan;
    private javax.swing.JLabel jLabelIdUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKeluhanMendesak;
    private javax.swing.JTextArea textDeskrips;
    // End of variables declaration//GEN-END:variables

    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    public void addActionListener(ActionListener x) {
        this.btnBack.addActionListener(x);
        this.btnTambah.addActionListener(x);
        //
    }

    public void addItemListener(ItemListener x) {
        this.ckMendesak.addItemListener(x);
        this.cbTemaKeluhan.addItemListener(x);
    }
    

}
