/*
 * 
 *  LICENSE
 * 
 */
package manajemenkomplain.keluhan.detailKeluhan;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author link
 */
public class viewDetailKeluhan extends javax.swing.JFrame {

    /**
     * Creates new form viewKeluhan
     */
    public viewDetailKeluhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKeluhan = new javax.swing.JLabel();
        lblIdKeluhan = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        lblTemaKeluhan = new javax.swing.JLabel();
        lblMendesak = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDeskripsi = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKeluhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblKeluhan.setText("Keluhan");

        lblIdKeluhan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdKeluhan.setText("idKeluhan    :  [idKeluhan]");

        lblIdUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdUser.setText("idUser         :  [idUser]");

        lblTemaKeluhan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTemaKeluhan.setText("Tema          : [TemaKeluhan]");

        lblMendesak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMendesak.setText("Mendesak    : [isMendesak]");

        lblDeskripsi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDeskripsi.setText("Deskripsi");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taDeskripsi.setEditable(false);
        taDeskripsi.setColumns(20);
        taDeskripsi.setRows(5);
        jScrollPane1.setViewportView(taDeskripsi);

        btnDelete.setText("Delete");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblKeluhan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdUser)
                            .addComponent(lblIdKeluhan)
                            .addComponent(lblTemaKeluhan)
                            .addComponent(lblMendesak)
                            .addComponent(lblDeskripsi)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnDelete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBack))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKeluhan)
                .addGap(18, 18, 18)
                .addComponent(lblIdKeluhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdUser)
                .addGap(18, 18, 18)
                .addComponent(lblTemaKeluhan)
                .addGap(18, 18, 18)
                .addComponent(lblMendesak)
                .addGap(18, 18, 18)
                .addComponent(lblDeskripsi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDetailKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDetailKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDetailKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDetailKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDetailKeluhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblIdKeluhan;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblKeluhan;
    private javax.swing.JLabel lblMendesak;
    private javax.swing.JLabel lblTemaKeluhan;
    private javax.swing.JTextArea taDeskripsi;
    // End of variables declaration//GEN-END:variables


///// getter
    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

 /// Setter

    public void setLblIdKeluhan(String t) {
        this.lblIdKeluhan.setText("idKeluhan    :   "+ t);
    }

    public void setLblIdUser(String t) {
        this.lblIdUser.setText("idUser         :  "+t);
    }


    public void setLblMendesak(String t) {
        this.lblMendesak.setText("Mendesak    : "+t);
    }

    public void setLblTemaKeluhan(String t) {
        this.lblTemaKeluhan.setText("Tema          : "+t);
    }

    public void setTaDeskripsi(String t) {
        this.taDeskripsi.setText(t);
    }
    
    public void addActionListener(ActionListener x){
        this.btnBack.addActionListener(x);
        this.btnDelete.addActionListener(x);
    }   

    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }

}
