/*
 * 
 *  LICENSE
 * 
 */
package manajemenkomplain.pengguna.Setting;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author link
 */
public class viewSettingAccount extends javax.swing.JFrame {

    /**
     * Creates new form viewSettingAccount
     */
    public viewSettingAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSetting = new javax.swing.JLabel();
        lblTypeFlav = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        lblNoTelp = new javax.swing.JLabel();
        tfNoTelp = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        btnChangeUserData = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblIdUserContent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSetting.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSetting.setText("Setting");

        lblTypeFlav.setText("Type : ");

        lblType.setText("[Tipe pengguna]");

        lblIdUser.setText("idUser :");

        lblNama.setText("Nama : ");

        tfNama.setText("[Nama]");

        lblAlamat.setText("Alamat :");

        tfAlamat.setText("[Alamat]");

        lblNoTelp.setText("NoTelp :");

        tfNoTelp.setText("[NoTelp]");

        btnChangePassword.setText("Ganti Password");

        btnChangeUserData.setText("Ganti Data");

        btnBack.setText("Back");

        lblIdUserContent.setText("[IdUser]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSetting))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTypeFlav)
                                    .addComponent(lblIdUser)
                                    .addComponent(lblNama)
                                    .addComponent(lblAlamat)
                                    .addComponent(lblNoTelp))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNama)
                                    .addComponent(tfAlamat)
                                    .addComponent(tfNoTelp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblType)
                                            .addComponent(lblIdUserContent))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChangePassword)
                                .addGap(39, 39, 39)
                                .addComponent(btnChangeUserData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnBack)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSetting)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeFlav)
                    .addComponent(lblType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUser)
                    .addComponent(lblIdUserContent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlamat)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoTelp)
                    .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnChangeUserData)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSettingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSettingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSettingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSettingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSettingAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeUserData;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblIdUserContent;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblTypeFlav;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoTelp;
    // End of variables declaration//GEN-END:variables
   

// getter
    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnChangePassword() {
        return btnChangePassword;
    }

    public JButton getBtnChangeUserData() {
        return btnChangeUserData;
    }

    public String getTfAlamat() {
        return tfAlamat.getText();
    }

    public String getTfNama() {
        return tfNama.getText();
    }

    public String getTfNoTelp() {
        return tfNoTelp.getText();
    }

    public String getLblIdUserContent() {
        return this.lblIdUserContent.getText();
    }

    /// Setter

    public void setLblType(String t) {
        this.lblType.setText(String.valueOf(t));
    }

    public void setTfAlamat(String t) {
        this.tfAlamat.setText(String.valueOf(t));
    }

    public void setTfNama(String t) {
        this.tfNama.setText(String.valueOf(t));
    }

    public void setTfNoTelp(String t) {
        this.tfNoTelp.setText(String.valueOf(t));
    }

    public void setLblIdUserContent(String t) {
        this.lblIdUserContent.setText(String.valueOf(t));
    }
    
    
    
    
    /// 
    public void addActionListener(ActionListener x) {
        this.btnBack.addActionListener(x);
        this.btnChangePassword.addActionListener(x);
        this.btnChangeUserData.addActionListener(x);
    }
    
    ////
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
}
